[View in Colaboratory](https://colab.research.google.com/github/rushi0109/Hotstar/blob/master/hotstar_2.ipynb)

In [4]:
!wget https://he-s3.s3.amazonaws.com/media/hackathon/machine-learning-indiahacks-2017/5f828822-4--4-hotstar_dataset.zip
!unzip 5f828822-4--4-hotstar_dataset.zip

--2018-08-28 17:51:54--  https://he-s3.s3.amazonaws.com/media/hackathon/machine-learning-indiahacks-2017/5f828822-4--4-hotstar_dataset.zip
Resolving he-s3.s3.amazonaws.com (he-s3.s3.amazonaws.com)... 52.219.40.104
Connecting to he-s3.s3.amazonaws.com (he-s3.s3.amazonaws.com)|52.219.40.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51766669 (49M) [application/zip]
Saving to: ‘5f828822-4--4-hotstar_dataset.zip’

5f828822-4--4-hotst 100%[===================>]  49.37M  9.06MB/s    in 15s     

2018-08-28 17:52:09 (3.39 MB/s) - ‘5f828822-4--4-hotstar_dataset.zip’ saved [51766669/51766669]

Archive:  5f828822-4--4-hotstar_dataset.zip
  inflating: sample_submission.csv   
  inflating: test_data.json          
  inflating: train_data.json         


In [0]:
import numpy as np
import pandas as pd
import re
train_data = pd.read_json('train_data.json',orient='index')

In [0]:
train_data['g1'] = [re.sub(pattern='\:\d+',repl='',string=x) for x in train_data['genres']]
train_data['g1'] = train_data['g1'].apply(lambda x: x.split(','))
t1 = pd.Series(train_data['g1']).apply(frozenset).to_frame(name='t_genre')
genreSet = frozenset.union(*t1.t_genre)

In [0]:
def string_genres_time(genre, string):
 if genre in string:
   prbmStr = string[string.index(genre) :]
   #print(prbmStr)
   problemStr = prbmStr[prbmStr.index(':')+1:]
   #print(problemStr)
   #print(problemStr.index(','))
   if ',' in problemStr:
     return int(problemStr[0:problemStr.index(',')])
   else:
     return int(problemStr[0:])
 else:
   return 0

In [0]:
def string_dow_time(genre, string):
 if genre in string:
   prbmStr = string[string.index(genre) :]
   #print(prbmStr)
   problemStr = prbmStr[prbmStr.index(':')+1:]
   #print(problemStr)
   #print(problemStr.index(','))
   if ',' in problemStr:
     return int(problemStr[0:problemStr.index(',')])
   else:
     return int(problemStr[0:])
 else:
   return 0

In [0]:
def string_tod_time(genre, string):
	if genre in string:
		prbmStr = string[string.index(genre) :]
		#print(prbmStr)
		problemStr = prbmStr[prbmStr.index(':')+1:]
		#print(problemStr)
		#print(problemStr.index(','))
		if ',' in problemStr:
			return int(problemStr[0:problemStr.index(',')])
		else:
			return int(problemStr[0:])
	else:
		todData = genre[1:]
		if todData in string:
			if string.index(todData) == 0:
				prbmStr = string[string.index(todData) :]
				#print(prbmStr)
				problemStr = prbmStr[prbmStr.index(':')+1:]
				#print(problemStr)
				#print(problemStr.index(','))
				if ',' in problemStr:
					return int(problemStr[0:problemStr.index(',')])
				else:
					return int(problemStr[0:])
			else:
				return 0
		else:
			return 0

In [0]:
for i in genreSet:
  train_data[i] = train_data["genres"].apply(lambda x : string_genres_time(i, x))

In [0]:
for i in np.arange(1,8):
  str_i = str(i) + ':'
  train_data[i] = train_data["dow"].apply(lambda x : string_dow_time(str_i, x))

In [0]:
for i in np.arange(0,24):
  str_i = ','+str(i)+':'
  colName = 'tod_'+str(i)
  train_data[colName] = train_data["tod"].apply(lambda x : string_genres_time(str_i, x))

In [0]:
train_data.drop(['g1','tod','dow','genres'],inplace=True,axis=1)

In [0]:
train_data.drop('cities',inplace=True,axis=1)

In [0]:
def get_int_value(param):
  return int(param[1:])

In [0]:
def getTimeList(titeString):
  return np.array([get_int_value(item) for item in re.findall('\:\d+',titeString)])

In [0]:
train_data['g2'] = [getTimeList(x) for x in train_data['titles']]
#train_data['g2'] = train_data['g2'].apply(lambda x: x.split(','))
#t1 = pd.Series(train_data['g2']).apply(frozenset).to_frame(name='t_titles')
#titlesSet = frozenset.union(*t1.t_titles)

In [18]:
train_data['title_mean'] = train_data['g2'].apply(np.mean)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)


In [19]:
train_data['title_median'] = train_data['g2'].apply(np.median)
train_data['title_sum'] = train_data['g2'].apply(np.sum)


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)


In [0]:
train_data['title_count'] = train_data['g2'].apply(len)

In [0]:
train_data.drop('g2',inplace=True,axis=1)

In [0]:
train_data.drop('titles',axis=1,inplace=True)

In [23]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200000 entries, train-1 to train-99999
Data columns (total 71 columns):
segment         200000 non-null object
Football        200000 non-null int64
Reality         200000 non-null int64
Comedy          200000 non-null int64
Documentary     200000 non-null int64
Travel          200000 non-null int64
Formula1        200000 non-null int64
Athletics       200000 non-null int64
Kabaddi         200000 non-null int64
Badminton       200000 non-null int64
LiveTV          200000 non-null int64
Sport           200000 non-null int64
Teen            200000 non-null int64
TalkShow        200000 non-null int64
Science         200000 non-null int64
Kids            200000 non-null int64
Table Tennis    200000 non-null int64
FormulaE        200000 non-null int64
Action          200000 non-null int64
Swimming        200000 non-null int64
Thriller        200000 non-null int64
Drama           200000 non-null int64
Mythology       200000 non-null int64
NA      

In [0]:
all_cols = list(train_data.columns)

In [0]:
all_cols.remove('title_count')
all_cols.remove('segment')

In [0]:
train_data[all_cols] = train_data[all_cols]/60

In [0]:
train_data[all_cols] = train_data[all_cols].fillna(0)

In [0]:
train_data[all_cols] = train_data[all_cols].astype(int)

In [0]:
train_data['segment'].replace('pos',1,inplace=True)
train_data['segment'].replace('neg',0,inplace=True)

In [30]:
train_data.head().T

train-1  train-10  train-100  train-1000  train-10000
segment             0         0          0           0            0
Football            0         0         68           0            0
Reality            79         0          0           0           22
Comedy              0         0          0           0            0
Documentary         0         0          0           0            0
Travel              0         0          0           0            0
Formula1            0         0          0           0            0
Athletics           0         0          0           0            0
Kabaddi             4         0          0           0            0
Badminton           0         0          0           0            0
LiveTV              0         0          0           0            0
Sport               0         0          0           0            0
Teen                0         0          0           0            0
TalkShow            0         0          0          10            0
Science             0         0          0           0            0
Kids                0         0          0           0            0
Table Tennis        0         0          0           0            0
FormulaE            0         0          0           0            0
Action              0         0          0           0            0
Swimming            0         0          0           0            0
Thriller            0         0          0           0            0
Drama               0         0          0           0           91
Mythology           0         0          0           0            0
NA                  0         0          0           0            0
Awards              0         0          0           0            0
Boxing              0         0          0           0            0
IndiaVsSa           0         0          0           0            0
Cricket          1372       260          0         128           54
Volleyball          0         0          0           0            0
Crime               0         0          0           0            0
...               ...       ...        ...         ...          ...
6                 276         0          0           0           81
7                 297        18          0           1           27
tod_0               0         0         40           0           39
tod_1               0        16          0           0            0
tod_2              39        26          8           0            0
tod_3               0        26          0           0            0
tod_4               0         0          0           0            0
tod_5               0         5          0           0            0
tod_6               0         0          0           0            0
tod_7               0         0          0           0            0
tod_8               0         4          0          10            0
tod_9               0         6          0           0            0
tod_10              0         6          0           0            0
tod_11              0         0          0           0            0
tod_12              5         0          0           0            0
tod_13              5         0          0           0            0
tod_14             36         0          0           0            0
tod_15             48        20          0           0           22
tod_16             28         8          0           0            0
tod_17            132         0          0           0            1
tod_18            100        28          0           0            0
tod_19            191        70          0          31            4
tod_20            364         6          0          40            0
tod_21            270        13          0          17            2
tod_22            148         3          0           0           68
tod_23             84         2          0          38           25
title_mean         24         3         34          17           15
ti

In [37]:
!pip install imblearn

    100% |████████████████████████████████| 153kB 5.0MB/s 


In [0]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [0]:
y_label = train_data.pop('segment')

In [0]:
X_train, X_test, y_train, y_test = train_test_split(train_data, y_label, test_size=0.3, random_state=9)

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.metrics import roc_auc_score,accuracy_score,confusion_matrix
seed = 9

In [35]:
kf = StratifiedKFold(n_splits=5,shuffle=True,random_state=seed)
pred_test_full =0
cv_score =[]
i=1
for train_index,test_index in kf.split(X_train,y_train):
    print('{} of KFold {}'.format(i,kf.n_splits))
    xtr,xvl = X_train.iloc[train_index],X_train.iloc[test_index]
    ytr,yvl = y_train.iloc[train_index],y_train.iloc[test_index]
    
    #model
    lr = LogisticRegression()
    lr.fit(xtr,ytr)
    score = roc_auc_score(yvl,lr.predict(xvl))
    print('ROC AUC score:',score)
    cv_score.append(score)   
    print('Test Accuracy: ',accuracy_score(yvl,lr.predict(xvl)))
    print('Train Accuracy: ',accuracy_score(ytr,lr.predict(xtr)))
    print(confusion_matrix(yvl,lr.predict(xvl)))
    print(classification_report(yvl,lr.predict(xvl)))
    print('------------------------------------------------------------------')
    print('Validation Accuracy ',accuracy_score(y_test,lr.predict(X_test)))
    print(confusion_matrix(y_test,lr.predict(X_test)))
    print(classification_report(y_test,lr.predict(X_test)))
    print('------------------------------------------------------------------')
    i+=1

1 of KFold 5
ROC AUC score: 0.5081278832993235
Test Accuracy:  0.9215385164815543
Train Accuracy:  0.9218832311002777
Confusion Matrix:  [[25761    99]
 [ 2098    43]]
2 of KFold 5
ROC AUC score: 0.5052241777747787
Test Accuracy:  0.9221071428571429
Train Accuracy:  0.9221875
Confusion Matrix:  [[25791    68]
 [ 2113    28]]
3 of KFold 5
ROC AUC score: 0.5078734297207909
Test Accuracy:  0.9218571428571428
Train Accuracy:  0.9215089285714285
Confusion Matrix:  [[25771    88]
 [ 2100    41]]
4 of KFold 5
ROC AUC score: 0.5057522725142615
Test Accuracy:  0.9215
Train Accuracy:  0.9218303571428571
Confusion Matrix:  [[25770    89]
 [ 2109    32]]
5 of KFold 5
ROC AUC score: 0.5076281581676041
Test Accuracy:  0.9210328940319297
Train Accuracy:  0.9217239131793467
Confusion Matrix:  [[25746   113]
 [ 2098    42]]


In [0]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_resampled, y_resampled = ros.fit_sample(X_train, y_train)

In [39]:
X_train.shape

(140000, 70)

In [40]:
kf = StratifiedKFold(n_splits=5,shuffle=True,random_state=seed)
pred_test_full =0
cv_score =[]
i=1
for train_index,test_index in kf.split(X_resampled,y_resampled):
    print('{} of KFold {}'.format(i,kf.n_splits))
    xtr,xvl = X_resampled[train_index],X_resampled[test_index]
    ytr,yvl = y_resampled[train_index],y_resampled[test_index]
    
    #model
    lr = LogisticRegression()
    lr.fit(xtr,ytr)
    score = roc_auc_score(yvl,lr.predict(xvl))
    print('ROC AUC score:',score)
    cv_score.append(score)   
    print('Test Accuracy: ',accuracy_score(yvl,lr.predict(xvl)))
    print('Train Accuracy: ',accuracy_score(ytr,lr.predict(xtr)))
    print('Confusion Matrix: ',confusion_matrix(yvl,lr.predict(xvl)))
    print('Validation Accuracy ',accuracy_score(y_test,lr.predict(X_test)))
    print('Validation Confusion Matrix: ',confusion_matrix(y_test,lr.predict(X_test)))
    print('------------------------------------------------------------------')
    i+=1

1 of KFold 5
ROC AUC score: 0.7123743232791957
Test Accuracy:  0.7123743232791957
Train Accuracy:  0.7102362813720562
Confusion Matrix:  [[19765  6095]
 [ 8781 17079]]
Validation Accuracy  0.7533833333333333
Validation Confusion Matrix:  [[42223 13226]
 [ 1571  2980]]
------------------------------------------------------------------
2 of KFold 5
ROC AUC score: 0.7101009319772613
Test Accuracy:  0.7101009319772613
Train Accuracy:  0.7121387897947543
Confusion Matrix:  [[19654  6205]
 [ 8788 17071]]
Validation Accuracy  0.75215
Validation Confusion Matrix:  [[42139 13310]
 [ 1561  2990]]
------------------------------------------------------------------
3 of KFold 5
ROC AUC score: 0.708960129935419
Test Accuracy:  0.708960129935419
Train Accuracy:  0.7093979910476909
Confusion Matrix:  [[19734  6125]
 [ 8927 16932]]
Validation Accuracy  0.7561
Validation Confusion Matrix:  [[42423 13026]
 [ 1608  2943]]
------------------------------------------------------------------
4 of KFold 5
ROC 

Random Forest

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [45]:
kf = StratifiedKFold(n_splits=5,shuffle=True,random_state=seed)
pred_test_full =0
cv_score =[]
i=1
for j in np.arange(1,50,5):
  for train_index,test_index in kf.split(X_resampled,y_resampled):
      print('{} and {} of KFold {}'.format(i,j,kf.n_splits))
      xtr,xvl = X_resampled[train_index],X_resampled[test_index]
      ytr,yvl = y_resampled[train_index],y_resampled[test_index]

      #model
      lr = RandomForestClassifier(max_depth=j)
      lr.fit(xtr,ytr)
      score = roc_auc_score(yvl,lr.predict(xvl))
      print('ROC AUC score:',score)
      cv_score.append(score)   
      print('Test Accuracy: ',accuracy_score(yvl,lr.predict(xvl)))
      print('Train Accuracy: ',accuracy_score(ytr,lr.predict(xtr)))
      print(confusion_matrix(yvl,lr.predict(xvl)))
      print(classification_report(yvl,lr.predict(xvl)))
      print('------------------------------------------------------------------')
      print('Validation Accuracy ',accuracy_score(y_test,lr.predict(X_test)))
      print(confusion_matrix(y_test,lr.predict(X_test)))
      print(classification_report(y_test,lr.predict(X_test)))
      print('------------------------------------------------------------------')
      i+=1

1 and 1 of KFold 5
ROC AUC score: 0.6242072699149265
Test Accuracy:  0.6242072699149265
Train Accuracy:  0.6245456127460459
[[18076  7784]
 [11652 14208]]
             precision    recall  f1-score   support

          0       0.61      0.70      0.65     25860
          1       0.65      0.55      0.59     25860

avg / total       0.63      0.62      0.62     51720

------------------------------------------------------------------
Validation Accuracy  0.6867
[[38703 16746]
 [ 2052  2499]]
             precision    recall  f1-score   support

          0       0.95      0.70      0.80     55449
          1       0.13      0.55      0.21      4551

avg / total       0.89      0.69      0.76     60000

------------------------------------------------------------------
2 and 1 of KFold 5
ROC AUC score: 0.7125178854557407
Test Accuracy:  0.7125178854557408
Train Accuracy:  0.7141110047661862
[[18622  7237]
 [ 7631 18228]]
             precision    recall  f1-score   support

          0  

In [47]:
kf = StratifiedKFold(n_splits=5,shuffle=True,random_state=seed)
pred_test_full =0
cv_score =[]
i=1
for j in np.arange(1,50,5):
  for train_index,test_index in kf.split(X_train,y_train):
      print('{} and {} of KFold {}'.format(i,j,kf.n_splits))
      xtr,xvl = X_train.iloc[train_index],X_train.iloc[test_index]
      ytr,yvl = y_train.iloc[train_index],y_train.iloc[test_index]

      #model
      lr = RandomForestClassifier(max_depth=j)
      lr.fit(xtr,ytr)
      score = roc_auc_score(yvl,lr.predict(xvl))
      print('ROC AUC score:',score)
      cv_score.append(score)   
      print('Test Accuracy: ',accuracy_score(yvl,lr.predict(xvl)))
      print('Train Accuracy: ',accuracy_score(ytr,lr.predict(xtr)))
      print(confusion_matrix(yvl,lr.predict(xvl)))
      print(classification_report(yvl,lr.predict(xvl)))
      print('------------------------------------------------------------------')
      print('Validation Accuracy ',accuracy_score(y_test,lr.predict(X_test)))
      print(confusion_matrix(y_test,lr.predict(X_test)))
      print(classification_report(y_test,lr.predict(X_test)))
      print('------------------------------------------------------------------')
      i+=1

1 and 1 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235384450555337
Train Accuracy:  0.9235439602139305
[[25860     0]
 [ 2141     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25860
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28001

------------------------------------------------------------------


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
2 and 1 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235357142857142
Train Accuracy:  0.9235446428571429
[[25859     0]
 [ 2141     0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28000

------------------------------------------------------------------
Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
3 and 1 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235357142857142
Train Accuracy:  0.9235446428571429
[[25859     0]
 [ 2141     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28000

---------------------

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
4 and 1 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235357142857142
Train Accuracy:  0.9235446428571429
[[25859     0]
 [ 2141     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28000

------------------------------------------------------------------


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
5 and 1 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235686988821029
Train Accuracy:  0.9235363969964554
[[25859     0]
 [ 2140     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2140

avg / total       0.85      0.92      0.89     27999

------------------------------------------------------------------


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
6 and 6 of KFold 5
ROC AUC score: 0.49996133023975253
Test Accuracy:  0.9234670190350345
Train Accuracy:  0.9235707461673764
[[25858     2]
 [ 2141     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25860
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28001

------------------------------------------------------------------
Validation Accuracy  0.9241333333333334
[[55448     1]
 [ 4551     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
8 and 6 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235357142857142
Train Accuracy:  0.9235535714285714
[[25859     0]
 [ 2141     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28000

------------------------------------------------------------------
Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
9 and 6 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235357142857142
Train Accuracy:  0.9235535714285714
[[25859     0]
 [ 2141     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2141

avg / total       0.85      0.92      0.89     28000

------------------------------------------------------------------
Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
10 and 6 of KFold 5
ROC AUC score: 0.5
Test Accuracy:  0.9235686988821029
Train Accuracy:  0.9235542539798752
[[25859     0]
 [ 2140     0]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25859
          1       0.00      0.00      0.00      2140

avg / total       0.85      0.92      0.89     27999

------------------------------------------------------------------
Validation Accuracy  0.92415
[[55449     0]
 [ 4551     0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.00      0.00      0.00      4551

avg / total       0.85      0.92      0.89     60000

------------------------------------------------------------------
11 and 11 of KFold 5
ROC AUC score: 0.500078856689977
Test Accuracy:  0.9232884539837863
Train Accuracy:  0.9255796926758275
[[25852     8]
 [ 2140     1]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     25860
          1       0.11      0.00      0.00      2141

avg / total       0.86      0.92      0.89     28001

------------------------------------------------------------------
Validation Accuracy  0.9239
[[55431    18]
 [ 4548     3]]
             precision    recall  f1-score   support

          0       0.92      1.00      0.96     55449
          1       0.14      0.00      0.00      4551

avg / total       0.86      0.92      0.89     60000

------

In [0]:
from imblearn.under_sampling import RandomUnderSampler
ros = RandomOverSampler()
X_undersampled, y_undersampled = ros.fit_sample(X_train, y_train)

In [50]:
kf = StratifiedKFold(n_splits=5,shuffle=True,random_state=seed)
pred_test_full =0
cv_score =[]
i=1
for j in np.arange(1,50,5):
  for train_index,test_index in kf.split(X_undersampled,y_undersampled):
      print('{} and {} of KFold {}'.format(i,j,kf.n_splits))
      xtr,xvl = X_undersampled[train_index],X_undersampled[test_index]
      ytr,yvl = y_undersampled[train_index],y_undersampled[test_index]

      #model
      lr = RandomForestClassifier(max_depth=j)
      lr.fit(xtr,ytr)
      score = roc_auc_score(yvl,lr.predict(xvl))
      print('ROC AUC score:',score)
      cv_score.append(score)   
      print('Test Accuracy: ',accuracy_score(yvl,lr.predict(xvl)))
      print('Train Accuracy: ',accuracy_score(ytr,lr.predict(xtr)))
      print(confusion_matrix(yvl,lr.predict(xvl)))
      print(classification_report(yvl,lr.predict(xvl)))
      print('------------------------------------------------------------------')
      print('Validation Accuracy ',accuracy_score(y_test,lr.predict(X_test)))
      print(confusion_matrix(y_test,lr.predict(X_test)))
      print(classification_report(y_test,lr.predict(X_test)))
      print('------------------------------------------------------------------')
      i+=1

1 and 1 of KFold 5
ROC AUC score: 0.6467130703789636
Test Accuracy:  0.6467130703789636
Train Accuracy:  0.6449060288487567
[[19430  6430]
 [11842 14018]]
             precision    recall  f1-score   support

          0       0.62      0.75      0.68     25860
          1       0.69      0.54      0.61     25860

avg / total       0.65      0.65      0.64     51720

------------------------------------------------------------------
Validation Accuracy  0.7325833333333334
[[41512 13937]
 [ 2108  2443]]
             precision    recall  f1-score   support

          0       0.95      0.75      0.84     55449
          1       0.15      0.54      0.23      4551

avg / total       0.89      0.73      0.79     60000

------------------------------------------------------------------
2 and 1 of KFold 5
ROC AUC score: 0.6993503229049847
Test Accuracy:  0.6993503229049848
Train Accuracy:  0.7009048986339511
[[13506 12353]
 [ 3196 22663]]
             precision    recall  f1-score   support

 

[103, 61593]

103